"""comment

Revision ID: eee77b6101ae
Revises: 
Create Date: 2020-11-29 01:16:55.340469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eee77b6101ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_embedding_storage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_embedding_storage_created_at'), 'project_embedding_storage', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_embedding_storage_project_id'), 'project_embedding_storage', ['project_id'], unique=False)
    op.create_table('science_job_embedding_storage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_science_job_embedding_storage_created_at'), 'science_job_embedding_storage', ['created_at'], unique=False)
    op.create_index(op.f('ix_science_job_embedding_storage_user_id'), 'science_job_embedding_storage', ['user_id'], unique=False)
    op.create_table('user_embedding_storage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_embedding_storage_created_at'), 'user_embedding_storage', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_embedding_storage_user_id'), 'user_embedding_storage', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_embedding_storage_user_id'), table_name='user_embedding_storage')
    op.drop_index(op.f('ix_user_embedding_storage_created_at'), table_name='user_embedding_storage')
    op.drop_table('user_embedding_storage')
    op.drop_index(op.f('ix_science_job_embedding_storage_user_id'), table_name='science_job_embedding_storage')
    op.drop_index(op.f('ix_science_job_embedding_storage_created_at'), table_name='science_job_embedding_storage')
    op.drop_table('science_job_embedding_storage')
    op.drop_index(op.f('ix_project_embedding_storage_project_id'), table_name='project_embedding_storage')
    op.drop_index(op.f('ix_project_embedding_storage_created_at'), table_name='project_embedding_storage')
    op.drop_table('project_embedding_storage')
    # ### end Alembic commands ###
